require_relative '../classes/musicalbum'
require_relative '../classes/genre'
require_relative '../classes/items'
require_relative '../classes/book'
require_relative '../classes/label'
require 'date'
require 'rspec'
